### PR TITLE
lexer: support multiline comments

### PR DESCRIPTION
**Pull request by ksmyth**
This PR adds support for multiline comments, as documented at http://www.mathworks.com/help/matlab/matlab_prog/comments.html

### CODE REVIEW

**Comment by RobBW** [comment]
Tests of Metamorph/smop multiline and comment features.

I am interested in using smop with the comment and multi-line doc string handling capabilities.
I noticed that the current version from Victorlei does not support this but that there has been ongoing work beyond version 0.23 to achieve it.  Smop appears to work with comments only in the commit [b426b80] of version 0.24 on 22/1/2014.  After that date the feature vanishes.

I noted that on 27/2/16 you advanced a change to the lexer code to support multi-line comments so
I downloaded your repository and tested for the comment/multi-line features on various builds.  
My results were as follows:

22/1/14 Version 0.24 commit b426b80 —> full support for comments and multi-line and the -n command option works.

15/9/14 Version 0.25.1	commit 84d40ad —> no support for comments
18/9/14 Version 0.25.4 	commit 0e3fed1 —> partially operating, inserts numbers instead of comments. Looks like it is trying to do the job.

7/10/14  Version 0.26	commit ccca612 —> no support for comments, version number ?

27/2/16 Version 0.23-148-g8a425ea  commit d6fdff6 —> no support for comments and version number inconsistent with its predecessors on the branch and date.  
Question, did the change work? or is there something I'm not doing correctly in using smop & git?

18/5/16 version 0.23 – 5828d12 — no support for comments. version number ?  

I've been trying to use smop to teach myself how to use GitHub and to learn Python based on my previous experience of Matlab.  Before I commit too much energy to reinventing a wheel I'd appreciate answers to the following three questions:

1) is there a good reason why the features in version 0.24 have been abandoned?
2) is there an easy way to merge  all Victorlei’s commits since 22/1/14 onto version 0.24 in my repository ?  (a newbie question I'm sure)
3)Will this generate more downstream problems than it's worth?

Any help would be appreciated.

**Comment by victorlei** [comment]
Guys, hello everybody.
What happenneed is that I committed a bunch of patches without properly
testing them first. Those patChes broke some code that was critical to me
So I undone them,. My health situation ccontributed to the mess, but now I
want to return to the project.

Victor
בתאריך 4 ביוני 2016 06:48,‏ "RobBW" <notifications@github.com> כתב:

**Comment by RobBW** [comment]
Thanks for the quick answer and good luck with the health. Been there done that and had a quadruple heart bypass!

Looking forward to your further input.
I think smop is a great piece of work and a vital tool to help newbies who want to move to Python with as little hassle as possible. 
Its also a great help to older people like myself who want to remain intellectually active but cannot and will not pay for MATLAB.

Getting comments etc working. is an important part of making smop a tool for routine use.
I said all this in a recent customer survey by the Anaconda people and was pleased to note that smop appeared in the pip repository not long after. Need to get it into Conda too as soon as practical.

I’m also playing around with some code to replace output ‘a.py’ with “filename.py” as way of applying my newbie Python skills. I’m also trying to package it with Platypus for myself and other Mac users.



Regards
Rob

**Comment by ksmyth** [comment]
@RobBW I added the `end` keyword in ca1779ff. I suspect you have two versions of smop in your `sys.path`. Running `main.py` on your input file works fine for me.

**Comment by RobBW** [comment]
Thanks, you were right.

**Pull request closed without merging**
