### PR TITLE
Change code for python 3

### PR DESCRIPTION
**Pull request by adriaanph**
These are the changes that I've had to make to be able to successfully convert my MATLAB code under python 3.

### CODE REVIEW

**Comment by HannoSpreeuw** [comment]
What is the best way to install smop for Python 3?

**Comment by HannoSpreeuw** [comment]
I tried
"
git clone https://github.com/adriaanph/smop
cd smop
python3 setup.py install".
No errors, apparently.
However, from within the Python 3 interpreter,
"import smop" gives
"Generating LALR tables
WARNING: 1 shift/reduce conflict".
Maybe this is fine.

**Comment by ceprio** [comment]
Looks like this pull request is not going through. Any reason why? 
What is the path to get smop running on python 3?

**Comment by RobBW** [comment]
Can I suggest you look to: [https://github.com/smop3/smop](url)
This site is where the good work of all those who put forward pull requests to [(https://github.com/victorlei/smop/)](url) be preserved.

**Pull request closed without merging**
